### ISSUE TITLE
Cannot read property 'headers' of undefined

### ISSUE THREAD

**Issue by biggamer145** [Faris90/Ogar3#18]
Whenever I try to run, I get this error

TypeError: Cannot read property 'headers' of undefined
    at GameServer.connectionEstablished (C:\Users\Josh\Downloads\Ogar3-master\Ogar3-master\GameServer.js:191:32)
    at WebSocketServer.emit (events.js:311:20)
    at WebSocketServer.completeUpgrade (C:\Users\Josh\Downloads\Ogar3-master\Ogar3-master\node_modules\ws\lib\websocket-server.js:431:5)
    at WebSocketServer.handleUpgrade (C:\Users\Josh\Downloads\Ogar3-master\Ogar3-master\node_modules\ws\lib\websocket-server.js:339:10)
    at Server.upgrade (C:\Users\Josh\Downloads\Ogar3-master\Ogar3-master\node_modules\ws\lib\websocket-server.js:114:16)
    at Server.emit (events.js:311:20)
    at onParserExecuteCommon (_http_server.js:642:14)
    at onParserExecute (_http_server.js:583:3)

Is there any fix to this?

**Comment by biggamer145** [comment]
Nevermind, I found a solution. Use an older node version (I used node v10.16.3)
