### ISSUE TITLE
After I run node index, I get an error like this 

### ISSUE THREAD

**Issue by parksisen** [Faris90/Ogar3#7]
**After I run node index, I get an error like this**

```
internal/fs/utils.js:307
    throw err;
    ^

Error: ENOENT: no such file or directory, rename './src/client/index.html' -> './src/client/index.html.bak'
    at Object.renameSync (fs.js:772:3)
    at GameServer.start (C:\Users\Administrator\Desktop\Ogar3-master\Ogar3-master\src\GameServer.js:144:6)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\Ogar3-master\Ogar3-master\src\index.js:32:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'rename',
  code: 'ENOENT',
  path: './src/client/index.html',
  dest: './src/client/index.html.bak'
}
```

**Comment by Faris90** [comment]
Click start.bat

**Comment by Faris90** [comment]
don't do it in cd src
do this instead:
`npm start`
If you have any further problems, tell me
